-- MySQL Script generated by MySQL Workbench
-- 07/04/17 22:47:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conceitotabacaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conceitotabacaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conceitotabacaria` DEFAULT CHARACTER SET utf8 ;
USE `conceitotabacaria` ;

-- -----------------------------------------------------
-- Table `conceitotabacaria`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conceitotabacaria`.`tb_grupos` (
  `gru_codigo` INT NOT NULL AUTO_INCREMENT,
  `gru_descricao` VARCHAR(45) NOT NULL,
  `gru_data_cadastro` DATETIME NOT NULL,
  `gru_data_alteracao` DATETIME NULL,
  PRIMARY KEY (`gru_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conceitotabacaria`.`tb_marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conceitotabacaria`.`tb_marcas` (
  `mar_codigo` INT NOT NULL AUTO_INCREMENT,
  `mar_descricao` VARCHAR(45) NOT NULL,
  `mar_grupo` INT NOT NULL,
  `mar_data_cadastro` DATETIME NOT NULL,
  `mar_data_alteracao` DATETIME NULL,
  PRIMARY KEY (`mar_codigo`),
  INDEX `mar_grupo_idx` (`mar_grupo` ASC),
  CONSTRAINT `mar_grupo`
    FOREIGN KEY (`mar_grupo`)
    REFERENCES `conceitotabacaria`.`tb_grupos` (`gru_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conceitotabacaria`.`tb_medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conceitotabacaria`.`tb_medidas` (
  `med_codigo` INT NOT NULL AUTO_INCREMENT,
  `med_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`med_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conceitotabacaria`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conceitotabacaria`.`tb_produtos` (
  `pro_codigo` INT NOT NULL AUTO_INCREMENT,
  `pro_descricao` VARCHAR(45) NOT NULL,
  `pro_peso` INT NOT NULL,
  `pro_medida` INT NOT NULL,
  `pro_marca` INT NOT NULL,
  `pro_data_cadastro` DATETIME NOT NULL,
  `pro_data_alteracao` DATETIME NULL,
  PRIMARY KEY (`pro_codigo`),
  INDEX `pro_marca_idx` (`pro_marca` ASC),
  INDEX `pro_medida_idx` (`pro_medida` ASC),
  CONSTRAINT `pro_marca`
    FOREIGN KEY (`pro_marca`)
    REFERENCES `conceitotabacaria`.`tb_marcas` (`mar_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pro_medida`
    FOREIGN KEY (`pro_medida`)
    REFERENCES `conceitotabacaria`.`tb_medidas` (`med_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conceitotabacaria`.`tb_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conceitotabacaria`.`tb_estoque` (
  `est_codigo` INT NOT NULL AUTO_INCREMENT,
  `est_cod_barras` INT NOT NULL,
  `est_preco_compra` FLOAT NOT NULL,
  `est_preco_venda` FLOAT NOT NULL,
  `est_produto` INT NOT NULL,
  `est_data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`est_codigo`),
  INDEX `est_produto_idx` (`est_produto` ASC),
  CONSTRAINT `est_produto`
    FOREIGN KEY (`est_produto`)
    REFERENCES `conceitotabacaria`.`tb_produtos` (`pro_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `conceitotabacaria`.`tb_lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conceitotabacaria`.`tb_lotes` (
  `lot_codigo` INT NOT NULL AUTO_INCREMENT,
  `lot_cod_barras` INT NOT NULL,
  `lot_quantidade` INT NOT NULL,
  `lot_preco_compra` FLOAT NOT NULL,
  `lot_preco_venda` FLOAT NULL,
  `lot_produto` INT NOT NULL,
  PRIMARY KEY (`lot_codigo`),
  INDEX `lot_produto_idx` (`lot_produto` ASC),
  CONSTRAINT `lot_produto`
    FOREIGN KEY (`lot_produto`)
    REFERENCES `conceitotabacaria`.`tb_produtos` (`pro_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
